<form id="bizumpayment_form" action="<?php echo $this->getUrl
('bizumpayment/payment/redirect'); ?>" method="post">
    <fieldset>
        <ul class="form-list">
            <li>
                <div class="field">
                    <label for="bizumpayment_number" class="required"><em>*</em><?php echo $this->__('Bizum Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="bizumpayment_number" name="bizumpayment_number" value="" class="input-text required-entry" />
                    </div>
                </div>
            </li>
        </ul>
        <p><?php echo $this->__('You will be redirected to the Bizum Payment Gateway after you place an order.') ?></p>
    </fieldset>
    <input type="submit" id="submit_bizumpayment_payment_form" value="<?php echo $this->__('Pay via Bizum Payment') ?>" />
</form>
  
