<div class="page-title">
    <h1><?php echo $this->__('Bizum Payment Gateway'); ?></h1>
</div>

<p><?php echo $this->__('You are now being redirected to Bizum Payment Gateway to complete your transaction.') ?></p>

<form action="<?php echo $this->getFormAction(); ?>" method="post" id="bizumpayment_payment_form">
    <input type="submit" id="submit_bizumpayment_payment_form" value="<?php echo $this->__('Click here if you are not redirected within 10 seconds.') ?>" />
    <?php foreach ($this->getFormFields() as $field => $value): ?>
        <input type="hidden" name="<?php echo $field; ?>" value="<?php echo $value; ?>" />
    <?php endforeach; ?>
</form>

<script type="text/javascript">
    document.getElementById('bizumpayment_payment_form').submit();
</script>
